"""
Seed script for Kyrgyz language track (A1-A2)
Создает стартовый набор уроков и практических упражнений на кыргызском языке.
"""

import json
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent))

from app.infrastructure.database.base import SessionLocal
from app.infrastructure.database.models import LessonModel, ExerciseModel
from app.domain.enums import EnglishLevel, ExerciseType, DifficultyLevel


def seed_kyrgyz_a2() -> None:
    db = SessionLocal()

    try:
        print("Запуск заполнения кыргызского трека A1-A2...")

        # Перезаполняем только кыргызский контент, английский не трогаем
        db.query(ExerciseModel).filter(ExerciseModel.language == "KYRGYZ").delete()
        db.query(LessonModel).filter(LessonModel.language == "KYRGYZ").delete()
        db.commit()

        lessons = [
            {
                "id": 201,
                "title": "Саламдашуу жана таанышуу",
                "description": "Базовые фразы приветствия и знакомства на кыргызском языке.",
                "level": EnglishLevel.A1,
                "language": "KYRGYZ",
                "order": 1,
                "xp_reward": 50,
            },
            {
                "id": 202,
                "title": "Кунумдук создор",
                "description": "Часто используемые слова и простые выражения для повседневной речи.",
                "level": EnglishLevel.A1,
                "language": "KYRGYZ",
                "order": 2,
                "xp_reward": 55,
            },
            {
                "id": 203,
                "title": "Суроо жана жооп",
                "description": "Как задавать простые вопросы и отвечать на них.",
                "level": EnglishLevel.A1,
                "language": "KYRGYZ",
                "order": 3,
                "xp_reward": 60,
            },
            {
                "id": 204,
                "title": "Уй-було жана достор",
                "description": "Лексика по теме семьи и общения с друзьями.",
                "level": EnglishLevel.A1,
                "language": "KYRGYZ",
                "order": 4,
                "xp_reward": 60,
            },
            {
                "id": 205,
                "title": "Откон чак (жонокой)",
                "description": "Первые конструкции для рассказа о прошлом.",
                "level": EnglishLevel.A2,
                "language": "KYRGYZ",
                "order": 1,
                "xp_reward": 65,
            },
            {
                "id": 206,
                "title": "Келер чак (план жана максат)",
                "description": "Выражение планов и намерений в будущем времени.",
                "level": EnglishLevel.A2,
                "language": "KYRGYZ",
                "order": 2,
                "xp_reward": 70,
            },
            {
                "id": 207,
                "title": "Салыштыруу жана сын атооч",
                "description": "Сравнительные конструкции и описания предметов.",
                "level": EnglishLevel.A2,
                "language": "KYRGYZ",
                "order": 3,
                "xp_reward": 70,
            },
            {
                "id": 208,
                "title": "Дукон, жол жана шаар",
                "description": "Практика языка в бытовых ситуациях: магазин, дорога, город.",
                "level": EnglishLevel.A2,
                "language": "KYRGYZ",
                "order": 4,
                "xp_reward": 75,
            },
        ]

        db.add_all([LessonModel(**lesson) for lesson in lessons])
        db.flush()

        exercises = [
            # Lesson 201
            {
                "id": 2001,
                "lesson_id": 201,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.EASY,
                "question": "'Салам' эмнени билдирет?",
                "correct_answer": "Привет",
                "options": json.dumps(["Привет", "Пока", "Спасибо", "Извините"]),
                "explanation": "'Салам' - это базовое приветствие.",
                "xp_reward": 10,
                "order": 1,
            },
            {
                "id": 2002,
                "lesson_id": 201,
                "language": "KYRGYZ",
                "type": ExerciseType.TYPE_ANSWER,
                "difficulty": DifficultyLevel.EASY,
                "question": "Переведите на кыргызский: 'Как дела?'",
                "correct_answer": "Кандайсын?",
                "options": None,
                "explanation": "Кандайсын? - неформальный вопрос о состоянии.",
                "xp_reward": 10,
                "order": 2,
            },
            {
                "id": 2003,
                "lesson_id": 201,
                "language": "KYRGYZ",
                "type": ExerciseType.TRANSLATION,
                "difficulty": DifficultyLevel.EASY,
                "question": "Сенин атың ким?",
                "correct_answer": "Как тебя зовут?",
                "options": None,
                "explanation": "Фраза используется при знакомстве.",
                "xp_reward": 10,
                "order": 3,
            },
            {
                "id": 2004,
                "lesson_id": 201,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Как правильно ответить на 'Рахмат'?",
                "correct_answer": "Ооба, рахмат",
                "options": json.dumps(["Ооба, рахмат", "Кайырлы тун", "Саламатта", "Жок"]),
                "explanation": "Вежливый ответ с благодарностью.",
                "xp_reward": 15,
                "order": 4,
            },
            # Lesson 202
            {
                "id": 2005,
                "lesson_id": 202,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.EASY,
                "question": "'Суу' деген соз кайсы?",
                "correct_answer": "Вода",
                "options": json.dumps(["Вода", "Хлеб", "Дом", "Книга"]),
                "explanation": "Суу = вода.",
                "xp_reward": 10,
                "order": 1,
            },
            {
                "id": 2006,
                "lesson_id": 202,
                "language": "KYRGYZ",
                "type": ExerciseType.TYPE_ANSWER,
                "difficulty": DifficultyLevel.EASY,
                "question": "Переведите на кыргызский: 'Я иду домой'",
                "correct_answer": "Мен уйго барам",
                "options": None,
                "explanation": "Базовая конструкция настоящего времени.",
                "xp_reward": 10,
                "order": 2,
            },
            {
                "id": 2007,
                "lesson_id": 202,
                "language": "KYRGYZ",
                "type": ExerciseType.TRANSLATION,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Биз мектепке барабыз",
                "correct_answer": "Мы идем в школу",
                "options": None,
                "explanation": "Биз = мы, мектепке = в школу.",
                "xp_reward": 15,
                "order": 3,
            },
            {
                "id": 2008,
                "lesson_id": 202,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Выберите правильный перевод: 'Тамак'",
                "correct_answer": "Еда",
                "options": json.dumps(["Еда", "Одежда", "Дорога", "Река"]),
                "explanation": "Тамак = еда/пища.",
                "xp_reward": 15,
                "order": 4,
            },
            # Lesson 203
            {
                "id": 2009,
                "lesson_id": 203,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.EASY,
                "question": "Как начинается вопрос 'Где?' на кыргызском?",
                "correct_answer": "Кайда",
                "options": json.dumps(["Кайда", "Качан", "Эмне", "Ким"]),
                "explanation": "Кайда = где.",
                "xp_reward": 10,
                "order": 1,
            },
            {
                "id": 2010,
                "lesson_id": 203,
                "language": "KYRGYZ",
                "type": ExerciseType.TYPE_ANSWER,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Переведите на русский: 'Сен кайда жашайсын?'",
                "correct_answer": "Где ты живешь?",
                "options": None,
                "explanation": "Сен = ты, кайда = где, жашайсын = живешь.",
                "xp_reward": 15,
                "order": 2,
            },
            {
                "id": 2011,
                "lesson_id": 203,
                "language": "KYRGYZ",
                "type": ExerciseType.TRANSLATION,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Сиз эмнени каалайсыз?",
                "correct_answer": "Что вы хотите?",
                "options": None,
                "explanation": "Вежливая форма вопроса.",
                "xp_reward": 15,
                "order": 3,
            },
            {
                "id": 2012,
                "lesson_id": 203,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.HARD,
                "question": "Выберите корректный ответ на 'Сен кайда иштейсин?'",
                "correct_answer": "Мен Бишкекте иштейм",
                "options": json.dumps([
                    "Мен Бишкекте иштейм",
                    "Мен кечээ бардым",
                    "Бул менин китебим",
                    "Сен жакшысын"
                ]),
                "explanation": "Ответ должен соответствовать вопросу о месте работы.",
                "xp_reward": 20,
                "order": 4,
            },
            # Lesson 204
            {
                "id": 2013,
                "lesson_id": 204,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.EASY,
                "question": "'Апа' деген ким?",
                "correct_answer": "Мама",
                "options": json.dumps(["Мама", "Папа", "Брат", "Друг"]),
                "explanation": "Апа = мама.",
                "xp_reward": 10,
                "order": 1,
            },
            {
                "id": 2014,
                "lesson_id": 204,
                "language": "KYRGYZ",
                "type": ExerciseType.TYPE_ANSWER,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Переведите: 'Менин иним студент'",
                "correct_answer": "Мой младший брат студент",
                "options": None,
                "explanation": "Ини - младший брат.",
                "xp_reward": 15,
                "order": 2,
            },
            {
                "id": 2015,
                "lesson_id": 204,
                "language": "KYRGYZ",
                "type": ExerciseType.TRANSLATION,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Биздин уй-було чон",
                "correct_answer": "Наша семья большая",
                "options": None,
                "explanation": "Чон = большой.",
                "xp_reward": 15,
                "order": 3,
            },
            {
                "id": 2016,
                "lesson_id": 204,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.HARD,
                "question": "Выберите верный перевод: 'Жакын дос'",
                "correct_answer": "Близкий друг",
                "options": json.dumps(["Близкий друг", "Старый дом", "Младшая сестра", "Новая работа"]),
                "explanation": "Жакын дос = близкий друг.",
                "xp_reward": 20,
                "order": 4,
            },
            # Lesson 205
            {
                "id": 2017,
                "lesson_id": 205,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "'Кечээ мен мектепке бардым' относится к какому времени?",
                "correct_answer": "Прошедшее",
                "options": json.dumps(["Прошедшее", "Настоящее", "Будущее", "Повелительное"]),
                "explanation": "Бардым указывает на прошедшее действие.",
                "xp_reward": 15,
                "order": 1,
            },
            {
                "id": 2018,
                "lesson_id": 205,
                "language": "KYRGYZ",
                "type": ExerciseType.TYPE_ANSWER,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Переведите: 'Я вчера работал'",
                "correct_answer": "Мен кечээ иштедим",
                "options": None,
                "explanation": "Кечээ = вчера, иштедим = работал.",
                "xp_reward": 15,
                "order": 2,
            },
            {
                "id": 2019,
                "lesson_id": 205,
                "language": "KYRGYZ",
                "type": ExerciseType.TRANSLATION,
                "difficulty": DifficultyLevel.HARD,
                "question": "Биз кино кордук",
                "correct_answer": "Мы посмотрели фильм",
                "options": None,
                "explanation": "Кордук = посмотрели.",
                "xp_reward": 20,
                "order": 3,
            },
            {
                "id": 2020,
                "lesson_id": 205,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.HARD,
                "question": "Выберите правильный вариант прошедшего времени для 'кел-'",
                "correct_answer": "келдим",
                "options": json.dumps(["келдим", "келем", "келемин", "келет"]),
                "explanation": "Келдим = я пришел.",
                "xp_reward": 20,
                "order": 4,
            },
            # Lesson 206
            {
                "id": 2021,
                "lesson_id": 206,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "'Эртен мен барам' означает:",
                "correct_answer": "Завтра я пойду",
                "options": json.dumps(["Завтра я пойду", "Я иду сейчас", "Я уже пришел", "Я не пойду"]),
                "explanation": "Эртен = завтра.",
                "xp_reward": 15,
                "order": 1,
            },
            {
                "id": 2022,
                "lesson_id": 206,
                "language": "KYRGYZ",
                "type": ExerciseType.TYPE_ANSWER,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Переведите: 'Мы будем учиться'",
                "correct_answer": "Биз окуйбуз",
                "options": None,
                "explanation": "Окуйбуз используется для будущего действия в контексте.",
                "xp_reward": 15,
                "order": 2,
            },
            {
                "id": 2023,
                "lesson_id": 206,
                "language": "KYRGYZ",
                "type": ExerciseType.TRANSLATION,
                "difficulty": DifficultyLevel.HARD,
                "question": "Сен эртен келесинби?",
                "correct_answer": "Ты придешь завтра?",
                "options": None,
                "explanation": "Вопрос о будущем действии.",
                "xp_reward": 20,
                "order": 3,
            },
            {
                "id": 2024,
                "lesson_id": 206,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.HARD,
                "question": "Как правильно сказать 'Я скоро позвоню' на кыргызском?",
                "correct_answer": "Мен жакында чалам",
                "options": json.dumps([
                    "Мен жакында чалам",
                    "Мен кечээ чалдым",
                    "Мен азыр уктап жатам",
                    "Сен азыр келдин"
                ]),
                "explanation": "Жакында чалам = скоро позвоню.",
                "xp_reward": 20,
                "order": 4,
            },
            # Lesson 207
            {
                "id": 2025,
                "lesson_id": 207,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "'Чонураак' что означает?",
                "correct_answer": "Больше",
                "options": json.dumps(["Больше", "Меньше", "Быстрее", "Тише"]),
                "explanation": "Форма сравнительной степени.",
                "xp_reward": 15,
                "order": 1,
            },
            {
                "id": 2026,
                "lesson_id": 207,
                "language": "KYRGYZ",
                "type": ExerciseType.TYPE_ANSWER,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Переведите: 'Эта дорога длиннее'",
                "correct_answer": "Бул жол узунураак",
                "options": None,
                "explanation": "Узунураак = длиннее.",
                "xp_reward": 15,
                "order": 2,
            },
            {
                "id": 2027,
                "lesson_id": 207,
                "language": "KYRGYZ",
                "type": ExerciseType.TRANSLATION,
                "difficulty": DifficultyLevel.HARD,
                "question": "Бул китеп кызыгыраак",
                "correct_answer": "Эта книга интереснее",
                "options": None,
                "explanation": "Кызыгыраак = интереснее.",
                "xp_reward": 20,
                "order": 3,
            },
            {
                "id": 2028,
                "lesson_id": 207,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.HARD,
                "question": "Выберите правильную форму: 'Бул уй ...' (больше)",
                "correct_answer": "чонураак",
                "options": json.dumps(["чонураак", "чон", "чоной", "чондум"]),
                "explanation": "Для сравнения используется чонураак.",
                "xp_reward": 20,
                "order": 4,
            },
            # Lesson 208
            {
                "id": 2029,
                "lesson_id": 208,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "'Дукон кайда?' переводится как:",
                "correct_answer": "Где магазин?",
                "options": json.dumps(["Где магазин?", "Когда магазин?", "Что купить?", "Кто продавец?"]),
                "explanation": "Кайда = где, дукон = магазин.",
                "xp_reward": 15,
                "order": 1,
            },
            {
                "id": 2030,
                "lesson_id": 208,
                "language": "KYRGYZ",
                "type": ExerciseType.TYPE_ANSWER,
                "difficulty": DifficultyLevel.MEDIUM,
                "question": "Переведите: 'Я иду на рынок'",
                "correct_answer": "Мен базарга барам",
                "options": None,
                "explanation": "Базарга барам = иду на рынок.",
                "xp_reward": 15,
                "order": 2,
            },
            {
                "id": 2031,
                "lesson_id": 208,
                "language": "KYRGYZ",
                "type": ExerciseType.TRANSLATION,
                "difficulty": DifficultyLevel.HARD,
                "question": "Сураныч, жолду корсотунуз",
                "correct_answer": "Пожалуйста, покажите дорогу",
                "options": None,
                "explanation": "Вежливая просьба в городской коммуникации.",
                "xp_reward": 20,
                "order": 3,
            },
            {
                "id": 2032,
                "lesson_id": 208,
                "language": "KYRGYZ",
                "type": ExerciseType.MULTIPLE_CHOICE,
                "difficulty": DifficultyLevel.HARD,
                "question": "Выберите корректный ответ на 'Бул жерде токтойбузбу?'",
                "correct_answer": "Ооба, бул жерде токтойбуз",
                "options": json.dumps([
                    "Ооба, бул жерде токтойбуз",
                    "Мен кечээ иштедим",
                    "Сен жакшы окуйсун",
                    "Бул китеп кызык"
                ]),
                "explanation": "Ответ подтверждает остановку в указанном месте.",
                "xp_reward": 20,
                "order": 4,
            },
        ]

        db.add_all([ExerciseModel(**exercise) for exercise in exercises])
        db.commit()

        print("Готово: кыргызский трек A1-A2 успешно добавлен.")
        print(f"Уроков: {len(lessons)}")
        print(f"Упражнений: {len(exercises)}")

    except Exception as exc:
        db.rollback()
        print(f"Ошибка seed-кыргызского контента: {exc}")
        raise
    finally:
        db.close()


if __name__ == '__main__':
    seed_kyrgyz_a2()
